#!/bin/bash
if [ -d "\$1" ]; then
    rm -f "\$1"/*.bak "\$1"/*.tmp "\$1"/*.backup
    echo "Файлы с расширениями .bak, .tmp, .backup удалены из директории \$1"
else
    echo "Ошибка: директория \$1 не существует"
fi
